[package]
name = "example-rust"
version = "0.1.0"
authors = ["Yevgeny Pats <yp@fuzzit.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
